services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production      
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
    networks:
      - frontend-network
    restart: unless-stopped

networks:
  frontend-network:
    driver: bridge 