services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production      
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - app-network
    restart: unless-stopped

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
      - ORIGIN=${ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongodb
    volumes:
      - ./src:/usr/src/app/src 
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

networks:  
  app-network:
    driver: bridge

volumes:
  mongodb_data:
