version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/viajes_db
      - JWT_SECRET=dev_secret
      - JWT_REFRESH_SECRET=dev_refresh_secret
      - COOKIE_SECRET=dev_cookie_secret
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
      - ./node_modules:/usr/src/app/node_modules
    command: yarn dev
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 