services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/viajes_db
      - JWT_SECRET=tu_secreto_super_seguro
      - JWT_REFRESH_SECRET=tu_refresh_secreto_super_seguro
      - COOKIE_SECRET=tu_cookie_secreto_super_seguro
    depends_on:
      - mongodb
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
